apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
spec:
  replicas: 3
  selector: 
     matchLabels:
        app: auth-dep
  template:
    metadata: 
      labels:
        app: auth-dep
    spec:
      containers:
        - name: auth
          image: filiprak2000/minikubenodeauth:latest

   